import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { AboutPageBody } from "@/components/about-page-body";
import { HOSTS, getHostBySlug } from "@/lib/constants";

/**
 * Per-host deep-link route (`/hosts/<slug>`).
 *
 * Social-share landing surface for the three hosts. When someone pastes
 * this URL into Facebook/X/LinkedIn/iMessage/Slack, the platform's scraper
 * fetches this page's HTML, reads its OG tags (including the per-host
 * card generated by the sibling `opengraph-image.tsx`) and renders the
 * preview. When a human visits, the full About body renders and that
 * host's modal (or mobile inline expansion) auto-opens on top — mirroring
 * what they'd see after clicking the card on `/about`.
 *
 * Pre-rendering: `generateStaticParams` returns all 3 host slugs so each
 * page becomes a static HTML file at build time. Cold scraper hits land
 * on fully-static HTML (no SSR latency) — important because Facebook's
 * scraper is known to bail on routes that respond slowly.
 *
 * Canonical: points at `/about#hosts` so search engines consolidate link
 * equity to the About page (where hosts are part of the narrative).
 * Social scrapers ignore canonical, so they still read this route's OG
 * tags — which is exactly what we want.
 *
 * Layout: renders the full About body via `<AboutPageBody />` with
 * `initialHostSlug` forwarded to `<Hosts />`. The Hosts component's own
 * mount effect scrolls `#hosts` into view and opens the matching host's
 * modal. Scrapers never execute that mount logic (they only read OG
 * meta), so there's zero impact on social previews.
 */

type RouteParams = Promise<{ slug: string }>;

export function generateStaticParams() {
  return HOSTS.map((h) => ({ slug: h.slug }));
}

export async function generateMetadata({
  params,
}: {
  params: RouteParams;
}): Promise<Metadata> {
  const { slug } = await params;
  const host = getHostBySlug(slug);
  if (!host) return {};

  const title = `${host.name} | Longevity Leadership Conference 2026`;
  const description = `${host.title} — hosting the Longevity Leadership Conference, April 30, 2026 in Los Angeles. ${host.bio}`;

  return {
    title,
    description,
    alternates: {
      // Canonical lives at `/about#hosts` — the deep-link routes exist for
      // social sharing, not SEO duplication. Google will treat /about as
      // authoritative; social scrapers still read this route's OG tags
      // because scrapers don't respect canonical.
      canonical: "/about#hosts",
    },
    openGraph: {
      title,
      description,
      type: "profile",
      url: `/hosts/${host.slug}`,
      // Images auto-populated by the sibling `opengraph-image.tsx` —
      // Next's file-based metadata convention reads that file, generates
      // the 1200×630 card at the edge, and appends its URL here
      // automatically. No manual `images: [...]` needed.
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      // Same file-based convention applies — `twitter-image.tsx` is
      // picked up automatically.
    },
  };
}

export default async function HostPage({
  params,
}: {
  params: RouteParams;
}) {
  const { slug } = await params;
  const host = getHostBySlug(slug);
  if (!host) notFound();

  return <AboutPageBody initialHostSlug={host.slug} />;
}
