import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { AboutPageBody } from "@/components/about-page-body";
import { EXPERIENCES, getExperienceBySlug } from "@/lib/constants";

/**
 * Per-experience deep-link route (`/experiences/<slug>`).
 *
 * Social-share landing surface for the three on-site activations. When
 * someone pastes this URL into Facebook/X/LinkedIn/iMessage/Slack, the
 * platform's scraper fetches this page's HTML, reads its OG tags
 * (including the per-experience card generated by the sibling
 * `opengraph-image.tsx`) and renders the preview. When a human visits,
 * the full About body renders and the carousel auto-scrolls to the
 * matching card on mount so they land on the exact activation they were
 * sent to read about — with the broader About context around it.
 *
 * Pre-rendering: `generateStaticParams` returns all 3 experience slugs
 * so each page becomes a static HTML file at build time — cold scraper
 * hits get fully-static HTML, no SSR latency.
 *
 * Canonical: points at `/about#iwa` so search engines consolidate link
 * equity to the About page (where experiences are part of the narrative
 * under the "Immersive Wellness Activations" section). Social scrapers
 * still read this route's OG tags because they don't respect canonical.
 *
 * Layout: renders the full About body via `<AboutPageBody />` with
 * `initialExperienceSlug` forwarded to `<Experiences />`. The Experiences
 * component's own mount effect scrolls `#experiences` into view and
 * centers the carousel on the matching activation. Scrapers never execute
 * that mount logic (they only read OG meta), so there's zero impact on
 * social previews.
 */

type RouteParams = Promise<{ slug: string }>;

export function generateStaticParams() {
  // EXPERIENCES schema keeps `id` as the URL slug (didn't rename the
  // field to avoid churning all the other places that read `experience.id`).
  return EXPERIENCES.map((e) => ({ slug: e.id }));
}

export async function generateMetadata({
  params,
}: {
  params: RouteParams;
}): Promise<Metadata> {
  const { slug } = await params;
  const exp = getExperienceBySlug(slug);
  if (!exp) return {};

  const title = `${exp.name} | Longevity Leadership Conference 2026`;
  const description = `${exp.tagline} presented by ${exp.sponsor}. ${exp.description}`;

  return {
    title,
    description,
    alternates: {
      // Canonical lives at `/about#iwa` — the deep-link routes exist for
      // social sharing, not SEO duplication. Google treats /about as
      // authoritative; social scrapers still read this route's OG tags.
      canonical: "/about#iwa",
    },
    openGraph: {
      title,
      description,
      type: "article",
      url: `/experiences/${exp.id}`,
      // Images auto-populated by the sibling `opengraph-image.tsx` —
      // Next's file-based metadata convention reads that file, generates
      // the 1200×630 card at the edge, and appends its URL here
      // automatically. No manual `images: [...]` needed.
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      // Same file-based convention applies — `twitter-image.tsx` is
      // picked up automatically.
    },
  };
}

export default async function ExperiencePage({
  params,
}: {
  params: RouteParams;
}) {
  const { slug } = await params;
  const exp = getExperienceBySlug(slug);
  if (!exp) notFound();

  return <AboutPageBody initialExperienceSlug={exp.id} />;
}
