import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { HomePageBody } from "@/components/home-page-body";
import { SPEAKERS, getSpeakerBySlug } from "@/lib/constants";

/**
 * Per-speaker deep-link route (`/speakers/<slug>`).
 *
 * Social-share landing surface: when someone pastes this URL into
 * Facebook/X/LinkedIn/iMessage/Slack, the platform's scraper fetches this
 * page's HTML and reads its OG tags (including the per-speaker OG image
 * generated by the sibling `opengraph-image.tsx`). When a human visits,
 * the page renders the full home body (hero, stats, vision, sponsors,
 * speakers carousel, topics, partner banner, gallery, agenda, subscribe)
 * with that speaker's modal auto-opened on top — giving them the same
 * in-context experience they'd get from clicking a card on the home page.
 *
 * Pre-rendering: `generateStaticParams` returns all speaker slugs so each
 * route becomes a static page at build time. Cold scraper hits land on
 * fully-static HTML (no SSR latency), which keeps slower scrapers like
 * Facebook's from timing out.
 *
 * Canonical: points at `/#speakers` so search engines consolidate link
 * equity to the home page rather than indexing 11 near-duplicate pages.
 * Social scrapers still read the per-route OG tags — canonical only
 * affects search indexing.
 *
 * Layout: renders the full home body via `<HomePageBody />` with
 * `initialSpeakerSlug` forwarded to `<Speakers />`. The Speakers
 * component's own mount effect scrolls `#speakers` into view and opens
 * the matching modal. Scrapers never execute that mount logic (they only
 * read OG meta), so there's zero impact on social previews.
 */

type RouteParams = Promise<{ slug: string }>;

export function generateStaticParams() {
  return SPEAKERS.map((s) => ({ slug: s.slug }));
}

export async function generateMetadata({
  params,
}: {
  params: RouteParams;
}): Promise<Metadata> {
  const { slug } = await params;
  const speaker = getSpeakerBySlug(slug);
  if (!speaker) return {};

  const title = `${speaker.name} | Longevity Leadership Conference 2026`;
  const description = `${speaker.role} — speaking at the Longevity Leadership Conference, April 30, 2026 in Los Angeles. ${speaker.bio.split("\n\n")[0]}`;

  return {
    title,
    description,
    alternates: {
      // Canonical lives at `/#speakers` — the deep-link routes exist for
      // social sharing, not SEO duplication. Google will treat the home
      // page as authoritative; social scrapers still read this route's
      // OG tags because they don't respect canonical.
      canonical: "/#speakers",
    },
    openGraph: {
      title,
      description,
      type: "profile",
      url: `/speakers/${speaker.slug}`,
      // Images are auto-populated by the sibling `opengraph-image.tsx`
      // — Next's file-based convention reads that file, generates the
      // 1200×630 card at the edge, and appends the image URL to this
      // metadata block automatically. No manual `images: [...]` needed.
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      // Same file-based convention applies — `twitter-image.tsx` is
      // picked up automatically.
    },
  };
}

export default async function SpeakerPage({
  params,
}: {
  params: RouteParams;
}) {
  const { slug } = await params;
  const speaker = getSpeakerBySlug(slug);
  if (!speaker) notFound();

  return <HomePageBody initialSpeakerSlug={speaker.slug} />;
}
